FROM node:18-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package.json package-lock.json ./

# Instalar dependencias
RUN npm install

# Copiar código fuente
COPY . .

# Configurar variables de entorno para desarrollo
ENV NODE_OPTIONS="--openssl-legacy-provider"
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true
ENV NODE_ENV=development
ENV REACT_APP_DEFAULT_PAGE_SIZE=10
ENV REACT_APP_MAX_PAGE_SIZE=100

# Exponer puerto de desarrollo
EXPOSE 3000

# Comando para desarrollo
CMD ["npm", "start"]
