FROM node:22-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package.json yarn.lock ./

# Instalar dependencias
RUN yarn install

# Copiar código fuente
COPY . .

# Configurar variables de entorno para desarrollo
ENV NODE_ENV=development

# Exponer puerto de desarrollo
EXPOSE 5000

# Comando para desarrollo
CMD ["yarn", "start:dev"]


